on:
  push:
    branches:
      - main

jobs:
  first:
    runs-on: ubuntu-latest
    outputs:
      blob: ${{ steps.blob.outputs.content }}
    steps:

      - name: blob
        id: blob
        run: |
          TEST="X_SERVICE_DEV"
          echo "content=$TEST" >> $GITHUB_OUTPUT

  call-reusable-testing-cicd:
    needs:
      - first
    uses: cordelou/gh-actions-poc/.github/workflows/reusable_wf.yml@main
    with:
      blob: ${{ needs.first.outputs.blob }}
