on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: test
        run: |
          echo "hello"

  call-reusable-testing-cicd:
    uses: cordelou/gh-actions-poc/.github/workflows/reusable_wf.yml@main
    with:
      blob: ${{ secrets.X_SERVICE_DEV }}
