on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: test
        run: |
          echo "hello"

  call-reusable-testing-cicd:
    uses: vwdfive/oneshop-ce/.github/workflows/reusable-testing-cicd.yml@feature/OS2TEAM3-48-create-resusable-workflow
    with:
      blob: ${{ secrets.X_SERVICE_DEV }}
