on:
  push:
    branches:
      - main

jobs:

  first:
    runs-on: ubuntu-latest
    outputs:
      blob: ${{ steps.blob.outputs.content }}
    steps:

      - name: Get Secret Name
        id: blob
        # language=bash
        run: |
          fake_input = "X"
          
          secret_name = ""
          if [[ "$fake_input" =~ ^(X)$ ]]; then
            secret_name = "X_SERVICE_DEV"
          else
            secret_name = "Y_SERVICE_DEV"
          fi
          
          echo "secret_name=$secret_name" >> $GITHUB_ENV
          

  call-reusable-testing-cicd:
    needs:
      - first
    uses: cordelou/gh-actions-poc/.github/workflows/reusable_wf.yml@main
    secrets:
      blob: ${{ secrets[secret_name] }}