on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      blob: ${{ steps.blob.outputs.content }}
    steps:

      - name: blob
        id: blob
        env:
          BLOB: ${{ secrets.X_SERVICE_DEV }}
        run: |
          echo "content=$BLOB" >> $GITHUB_OUTPUT

  call-reusable-testing-cicd:
    needs: test
    uses: cordelou/gh-actions-poc/.github/workflows/reusable_wf.yml@main
    secrets:
      blob: ${{ secrets.X_SERVICE_DEV }}
