on:
  push:
    branches:
      - main

jobs:

  first:
    runs-on: ubuntu-latest
    outputs:
      blob: ${{ steps.blob.outputs.SECRET_NAME }}
    steps:

      - name: Get Secret Name
        id: blob
        # language=bash
        run: |
          FAKE_INPUT="X"
          
          SECRET_NAME=""
          if [[ "$FAKE_INPUT" =~ ^(X)$ ]]; then
            SECRET_NAME="X_SERVICE_DEV"
          else
            SECRET_NAME="Y_SERVICE_DEV"
          fi
          
          echo "SECRET_NAME=$SECRET_NAME" >> "$GITHUB_OUTPUT"

  call-reusable-testing-cicd:
    needs:
      - first
    uses: cordelou/gh-actions-poc/.github/workflows/reusable_wf.yml@main
    secrets:
      blob: ${{ secrets[ needs.first.outputs.blob ] }}