on:
  push:
    branches:
      - main

jobs:

  first:
    runs-on: ubuntu-latest
    outputs:
      blob: ${{ steps.blob.outputs.content }}
    steps:

      - name: Get Secret Name
        # language=bash
        run: |
          FAKE_INPUT="X"
          
          SECRET_NAME=""
          if [[ "$FAKE_INPUT" =~ ^(X)$ ]]; then
            SECRET_NAME="X_SERVICE_DEV"
          else
            SECRET_NAME="Y_SERVICE_DEV"
          fi
          
          # echo "secret_name=$secret_name" >> $GITHUB_ENV
          echo "SECRET_NAME=$SECRET_NAME" >> "$GITHUB_ENV"

      - name: test
        # language=bash
        run: |
          echo ${{ env.SECRET_NAME }}

  call-reusable-testing-cicd:
    needs:
      - first
    uses: cordelou/gh-actions-poc/.github/workflows/reusable_wf.yml@main
    secrets:
      blob: ${{ SECRET_NAME }}