on:
  push:
    branches:
      - main

jobs:
  first:
    runs-on: ubuntu-latest
    outputs:
      blob: ${{ steps.blob.outputs.content }}
    steps:

      - name: blob
        id: blob
        run: |
          TEST="foo.bar.prop=aaa"
          echo "content=$TEST" >> $GITHUB_OUTPUT

  test2:
    runs-on: ubuntu-latest
    needs:
      - first
    steps:

      - name: test
        env:
          TEST: ${{ needs.first.outputs.blob }}
        run: |
          echo $TEST

  call-reusable-testing-cicd:
    needs:
      - first
    uses: cordelou/gh-actions-poc/.github/workflows/reusable_wf.yml@main
    secrets:
      blob: ${{ needs.first.outputs.blob }}
