on:
  workflow_call:
    secrets:
      blob:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup JAVA Environment
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Configure Test Environment
        # language=bash
        run: |
          echo "${{ secrets.blob }}" > .env

      - name: Test
        # language=bash
        run: |
          mvn clean install