on:
  workflow_call:
    secrets:
      blob:
        required: true

env:
  NAMES: ${{ inputs.blob }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Setup JAVA Environment
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17